[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.intl",
  "php83Extensions.zip",
  "php83Extensions.exif"
]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "php artisan key:generate",
  "php artisan migrate --force"
]